In [1]:
import pandas as pd
df=pd.read_csv("meets.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'meets.csv'

In [52]:
df.head()

,MeetID,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
0,0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
1,1,365strong/1602,365Strong,2016-11-19,USA,MO,Ozark,Thanksgiving Powerlifting Classic
2,2,365strong/1603,365Strong,2016-07-09,USA,NC,Charlotte,Charlotte Europa Games
3,3,365strong/1604,365Strong,2016-06-11,USA,SC,Rock Hill,Carolina Cup Push Pull Challenge
4,4,365strong/1605,365Strong,2016-04-10,USA,SC,Rock Hill,Eastern USA Challenge

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8482 entries, 0 to 8481
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MeetID       8482 non-null   int64
 1   MeetPath     8482 non-null   object
 2   Federation   8482 non-null   object
 3   Date         8482 non-null   object
 4   MeetCountry  8482 non-null   object
 5   MeetState    5496 non-null   object
 6   MeetTown     6973 non-null   object
 7   MeetName     8482 non-null   object
dtypes: int64(1), object(7)
memory usage: 530.3+ KB

In [56]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
8477    False
8478    False
8479    False
8480    False
8481    False
Length: 8482, dtype: bool

In [70]:
df.isnull().sum()

MeetID            0
MeetPath          0
Federation        0
Date              0
MeetCountry       0
MeetState      2986
MeetTown       1509
MeetName          0
dtype: int64

In [82]:
df["MeetState"]=df["MeetState"].fillna("Fire")

In [84]:
df.isnull().sum()

MeetID            0
MeetPath          0
Federation        0
Date              0
MeetCountry       0
MeetState         0
MeetTown       1509
MeetName          0
dtype: int64

In [16]:
df.describe()

            MeetID
count  8482.000000
mean   4240.500000
std    2448.686825
min       0.000000
25%    2120.250000
50%    4240.500000
75%    6360.750000
max    8481.000000

In [22]:
df[0:4]

,MeetID,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
0,0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
1,1,365strong/1602,365Strong,2016-11-19,USA,MO,Ozark,Thanksgiving Powerlifting Classic
2,2,365strong/1603,365Strong,2016-07-09,USA,NC,Charlotte,Charlotte Europa Games
3,3,365strong/1604,365Strong,2016-06-11,USA,SC,Rock Hill,Carolina Cup Push Pull Challenge

In [34]:
df.iloc[0:4]

,MeetID,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
0,0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
1,1,365strong/1602,365Strong,2016-11-19,USA,MO,Ozark,Thanksgiving Powerlifting Classic
2,2,365strong/1603,365Strong,2016-07-09,USA,NC,Charlotte,Charlotte Europa Games
3,3,365strong/1604,365Strong,2016-06-11,USA,SC,Rock Hill,Carolina Cup Push Pull Challenge

In [40]:
df.loc[0:,"MeetID":"MeetCountry"]

      MeetID                   MeetPath Federation        Date MeetCountry
0          0             365strong/1601  365Strong  2016-10-29         USA
1          1             365strong/1602  365Strong  2016-11-19         USA
2          2             365strong/1603  365Strong  2016-07-09         USA
3          3             365strong/1604  365Strong  2016-06-11         USA
4          4             365strong/1605  365Strong  2016-04-10         USA
...      ...                        ...        ...         ...         ...
8477    8477            xpc/2015-finals        XPC  2015-03-06         USA
8478    8478  xpc/2016-bench-freak-show        XPC  2016-03-04         USA
8479    8479      xpc/2016-elite-finals        XPC  2016-03-04         USA
8480    8480        xpc/2016-pro-finals        XPC  2016-03-05         USA
8481    8481            xpc/2017-finals        XPC  2017-03-03         USA

[8482 rows x 5 columns]

In [46]:
df["Meet"]

      MeetID Federation
0          0  365Strong
1          1  365Strong
2          2  365Strong
3          3  365Strong
4          4  365Strong
...      ...        ...
8477    8477        XPC
8478    8478        XPC
8479    8479        XPC
8480    8480        XPC
8481    8481        XPC

[8482 rows x 2 columns]

In [50]:
df[df.MeetCountry=='USA']

,MeetID,MeetPath,Federation,Date,MeetCountry,MeetState,MeetTown,MeetName
0,0,365strong/1601,365Strong,2016-10-29,USA,NC,Charlotte,2016 Junior & Senior National Powerlifting Cha...
1,1,365strong/1602,365Strong,2016-11-19,USA,MO,Ozark,Thanksgiving Powerlifting Classic
2,2,365strong/1603,365Strong,2016-07-09,USA,NC,Charlotte,Charlotte Europa Games
3,3,365strong/1604,365Strong,2016-06-11,USA,SC,Rock Hill,Carolina Cup Push Pull Challenge
4,4,365strong/1605,365Strong,2016-04-10,USA,SC,Rock Hill,Eastern USA Challenge
...,...,...,...,...,...,...,...,...
8477,8477,xpc/2015-finals,XPC,2015-03-06,USA,OH,Columbus,2015 XPC
8478,8478,xpc/2016-bench-freak-show,XPC,2016-03-04,USA,OH,Columbus,2016 XPC Bench Freak Show
8479,8479,xpc/2016-elite-finals,XPC,2016-03-04,USA,OH,Columbus,2016 XPC Elite Finals
8480,8480,xpc/2016-pro-finals,XPC,2016-03-05,USA,OH,Columbus,2016 XPC PRO Finals
8481,8481,xpc/2017-finals,XPC,2017-03-03,USA,OH,Columbus,2017 XPC Finals